apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
# Secret com a connection string do Postgres (ajuste conforme seu banco)
apiVersion: v1
kind: Secret
metadata:
  name: nauth-secrets
  namespace: apps
type: Opaque
stringData:
  ConnectionStrings__Default: "Host=postgres.db.svc.cluster.local;Port=5432;Database=appdb;Username=appuser;Password=appsecret;Pooling=true;SSL Mode=Disable;"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nauth
  namespace: apps
  labels:
    app: nauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nauth
  template:
    metadata:
      labels:
        app: nauth
    spec:
      # Se você rotulou o worker como emagine=true, descomente:
      # nodeSelector:
      #   emagine: "true"
      containers:
        - name: nauth
          image: emagine/nauth:local     # mesma tag que você carregou no kind
          imagePullPolicy: IfNotPresent
          #imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080        # vamos servir HTTP (mais simples)
            # Se quiser também expor HTTPS interno depois, descomente:
            # - name: https
            #   containerPort: 8443
          envFrom:
            - secretRef:
                name: nauth-secrets
          env:
            # Força o Kestrel a escutar HTTP em 8080 (evita redirecionar para HTTPS)
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: nauth
  namespace: apps
  labels:
    app: nauth
spec:
  type: ClusterIP
  selector:
    app: nauth
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    # Se habilitar HTTPS no container, você pode expor também:
    # - name: https
    #   port: 443
    #   targetPort: 8443
---
# Ingress (opcional) — requer ingress-nginx com classe "nginx"
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nauth
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    # Substitua <IP_DO_WSL> pelo IP do WSL (ex.: 172.30.x.x)
    - host: nauth.172.30.125.117.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nauth
                port:
                  number: 80
