# Stage 1: Build the React Application
FROM node:18-alpine as build

WORKDIR /app
COPY package*.json ./

COPY . .
RUN npm install
RUN npm run build

# Stage 2: Setup the Nginx Server to serve the React Application
FROM nginx:alpine 
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 3001

CMD ["nginx", "-g", "daemon off;"]
